USE [master]
GO

EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'INDT.TravelRoute'
GO

IF EXISTS (SELECT 1 FROM sys.databases WHERE [name] = N'INDT.TravelRoute')
BEGIN
ALTER DATABASE [INDT.TravelRoute] SET SINGLE_USER WITH ROLLBACK IMMEDIATE

DROP DATABASE [INDT.TravelRoute]

END
GO

CREATE DATABASE [INDT.TravelRoute]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [INDT.TravelRoute].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [INDT.TravelRoute] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET ARITHABORT OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [INDT.TravelRoute] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [INDT.TravelRoute] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET  DISABLE_BROKER 
GO

ALTER DATABASE [INDT.TravelRoute] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [INDT.TravelRoute] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET RECOVERY FULL 
GO

ALTER DATABASE [INDT.TravelRoute] SET  MULTI_USER 
GO

ALTER DATABASE [INDT.TravelRoute] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [INDT.TravelRoute] SET DB_CHAINING OFF 
GO

ALTER DATABASE [INDT.TravelRoute] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [INDT.TravelRoute] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [INDT.TravelRoute] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [INDT.TravelRoute] SET QUERY_STORE = OFF
GO

ALTER DATABASE [INDT.TravelRoute] SET  READ_WRITE 
GO


USE [INDT.TravelRoute]
GO

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'dbo' AND name like 'Routes')  
   DROP TABLE [dbo].[Routes]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Routes](
	[Id] [uniqueidentifier] NOT NULL DEFAULT NewSequentialID(),
	[From] [varchar](3) NOT NULL,
	[To] [varchar](3) NOT NULL,
	[Value] [decimal](18,3) NOT NULL,
	[InclusionDate] [datetime] NOT NULL DEFAULT GETDATE(),
	[LastUpdateDate] [datetime] NOT NULL DEFAULT GETDATE(),
 CONSTRAINT [PK_Routes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO


